[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.8.2"
regex = "1.11.1"
rocket = { version = "0.5.0", features = ["json"] }
serde = "1.0.202"
serde_json = "1.0.117"
tokio = "1.37.0"
toml = "0.8.13"
zmq = "0.10.0"
